name: Deploy to AWS Lambda

on:
  push:
    branches:
      - main  # Change to your main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install

      - name: Zip Project for Deployment
        run: zip -r deploy.zip . -x "node_modules/*" "tests/*" ".git/*"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload to S3
        run: aws s3 cp deploy.zip s3://${{ secrets.S3_BUCKET_NAME }}/deploy.zip

      - name: Deploy Lambda Function
        run: |
          aws lambda update-function-code \
            --function-name MyInvoiceLambda \
            --s3-bucket ${{ secrets.S3_BUCKET_NAME }} \
            --s3-key deploy.zip
